global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using PizzaPlace.Application.Common.Models;
global using PizzaPlace.Domain.Entities;
global using PizzaPlace.Application.Common.Helpers.CsvDtos;
